services:
  db:
    image: ${POSTGRESQL_IMAGE:-postgres:17.6-alpine3.22}
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: my-market
  redis:
    image: ${REDIS_IMAGE:-redis:8.4.0-alpine}
    container_name: redis
    ports:
      - "6379:6379"
  minio:
    image: ${MINIO_IMAGE:-minio/minio:RELEASE.2025-09-07T16-13-09Z}
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minio123}
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "minio", "health", "live"]
      interval: 10s
      timeout: 5s
      retries: 5