services:
  db:
    image: postgres:17.6-alpine3.22
    container_name: my-market-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: my-market
  minio:
    image: minio/minio:latest
    container_name: my-market-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minio123}
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "minio", "health", "live"]
      interval: 10s
      timeout: 5s
      retries: 5